---
title: "Graph sample"
author: 'Dirkje Verhoeven, Dolf Andringa, Annelies Andringa: Marine Conservation Philippines'
date: "19 July 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load('data.RDa') #load the data
library('ggplot2')
df.sample_data <- merge(x=df.sample_data, y=df.sites, by.x="location", by.y="name", all.x=TRUE)
```

A graph with the distance to seagrass and the abundance of *Abudefduf sexfasciatus*
See also http://www.r-bloggers.com/ggplot2-cheatsheet-for-scatterplots/ and http://www.cookbook-r.com/Graphs/Scatterplots_(ggplot2)/ for more info. The line represents the mean of the abundance of the species plotted for each distance to seagrass
```{r plot}
#setup a plot and define the axes
plt <- ggplot(df.sample_data, aes(x=log(distance_seagrass), y=abudefduf_sexfasciatus)) + xlab('Distance to seagrass (m)') + ylab('Abundance Abudefduf sexfasciatus')
#add the points
plt <- plt + geom_point()
#calculate mean abundance for each distance_seagrass so we can plot a line with that info
agg <- aggregate(df.sample_data$abudefduf_sexfasciatus, by=list(distance_seagrass=df.sample_data$distance_seagrass), FUN=mean)
agg$abudefduf_sexfasciatus <- agg$x #just rename the variable so it is the same as the original axis
#add a line to the plot with the aggregated data.
plt <- plt + geom_line(data=agg)
plt #show the plot
```

It is also possible to show a plot with the predicted values according to a GLM in the polt as a line.
```{r plot_glm}
#first create the glm model.
f <- df.sample_data$abudefduf_sexfasciatus ~ log(df.sample_data$distance_seagrass) * log(df.sample_data$size_seagrass) * df.sample_data$mpa * df.sample_data$north * df.sample_data$depth
model <- glm(f, family='poisson')

#then calculate the mean predicted abundance (based on the model) for each distance_seagrass because that is what we want to plot.
agg <- aggregate(model$fitted.values, by=list(distance_seagrass = df.sample_data$distance_seagrass), FUN=mean)
agg$abudefduf_sexfasciatus <- agg$x

#make the plot:
plt <- ggplot(df.sample_data, aes(x=log(distance_seagrass), y=abudefduf_sexfasciatus)) + xlab('ln(Distance to seagrass) (m)') + ylab('Abundance Abudefduf sexfasciatus')
#add the points
plt <- plt + geom_point()
#add the line
plt <- plt + geom_line(data=agg, color="red")
#show the plot
plt
```

#Seagrass

```{r abu_vaig_plot}

plt <- ggplot(df.sample_data, aes(x=log(distance_seagrass), y=abudefduf_vaigiensis)) + xlab('Distance to seagrass (m)') + ylab('Abundance Abudefduf vaigiensis')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$abudefduf_vaigiensis, by=list(distance_seagrass=df.sample_data$distance_seagrass), FUN=mean)
agg$abudefduf_vaigiensis <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r che_qui}

plt <- ggplot(df.sample_data, aes(x=log(distance_seagrass), y=cheilodipterus_quinquelineatus)) + xlab('Distance to seagrass (m)') + ylab('Abundance Cheilodipterus quinquelineatus')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$cheilodipterus_quinquelineatus, by=list(distance_seagrass=df.sample_data$distance_seagrass), FUN=mean)
agg$cheilodipterus_quinquelineatus <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r hal_hor}

plt <- ggplot(df.sample_data, aes(x=log(distance_seagrass), y=halichoeres_hortulanus)) + xlab('Distance to seagrass (m)') + ylab('Abundance Halichoeres hortulanus')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$halichoeres_hortulanus, by=list(distance_seagrass=df.sample_data$distance_seagrass), FUN=mean)
agg$halichoeres_hortulanus <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r lut_ful}

plt <- ggplot(df.sample_data, aes(x=log(distance_seagrass), y=lutjanus_fulviflamma)) + xlab('Distance to seagrass (m)') + ylab('Abundance Lutjanus fulviflamma')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$lutjanus_fulviflamma, by=list(distance_seagrass=df.sample_data$distance_seagrass), FUN=mean)
agg$lutjanus_fulviflamma <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r mul_fla}

plt <- ggplot(df.sample_data, aes(x=log(distance_seagrass), y=mulloidichthys_flavolineatus)) + xlab('Distance to seagrass (m)') + ylab('Abundance Mulloidichthys flavolineatus')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$mulloidichthys_flavolineatus, by=list(distance_seagrass=df.sample_data$distance_seagrass), FUN=mean)
agg$mulloidichthys_flavolineatus <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r par_bar}

plt <- ggplot(df.sample_data, aes(x=log(distance_seagrass), y=parupeneus_barberinoides)) + xlab('Distance to seagrass (m)') + ylab('Abundance Parupeneus barberinoides')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$parupeneus_barberinoides, by=list(distance_seagrass=df.sample_data$distance_seagrass), FUN=mean)
agg$parupeneus_barberinoides <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r par_bar2}

plt <- ggplot(df.sample_data, aes(x=log(distance_seagrass), y=parupeneus_barberinus)) + xlab('Distance to seagrass (m)') + ylab('Abundance Parupeneus barberinus')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$parupeneus_barberinus, by=list(distance_seagrass=df.sample_data$distance_seagrass), FUN=mean)
agg$parupeneus_barberinus <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

#Mangroves

```{r m_abu_sex_plot}

plt <- ggplot(df.sample_data, aes(x=log(distance_mangroves), y=abudefduf_sexfasciatus)) + xlab('Distance to mangroves (m)') + ylab('Abundance Abudefduf sexfasciatus')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$abudefduf_sexfasciatus, by=list(distance_mangroves=df.sample_data$distance_mangroves), FUN=mean)
agg$abudefduf_sexfasciatus <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r m_abu_vaig_plot}

plt <- ggplot(df.sample_data, aes(x=log(distance_mangroves), y=abudefduf_vaigiensis)) + xlab('Distance to mangroves (m)') + ylab('Abundance Abudefduf vaigiensis')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$abudefduf_vaigiensis, by=list(distance_mangroves=df.sample_data$distance_mangroves), FUN=mean)
agg$abudefduf_vaigiensis <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r m_che_qui}

plt <- ggplot(df.sample_data, aes(x=log(distance_mangroves), y=cheilodipterus_quinquelineatus)) + xlab('Distance to mangroves (m)') + ylab('Abundance Cheilodipterus quinquelineatus')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$cheilodipterus_quinquelineatus, by=list(distance_mangroves=df.sample_data$distance_mangroves), FUN=mean)
agg$cheilodipterus_quinquelineatus <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r m_hal_hor}

plt <- ggplot(df.sample_data, aes(x=log(distance_mangroves), y=halichoeres_hortulanus)) + xlab('Distance to mangroves (m)') + ylab('Abundance Halichoeres hortulanus')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$halichoeres_hortulanus, by=list(distance_mangroves=df.sample_data$distance_mangroves), FUN=mean)
agg$halichoeres_hortulanus <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r m_lut_ful}

plt <- ggplot(df.sample_data, aes(x=log(distance_mangroves), y=lutjanus_fulviflamma)) + xlab('Distance to mangroves (m)') + ylab('Abundance Lutjanus fulviflamma')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$lutjanus_fulviflamma, by=list(distance_mangroves=df.sample_data$distance_mangroves), FUN=mean)
agg$lutjanus_fulviflamma <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r m_mul_fla}

plt <- ggplot(df.sample_data, aes(x=log(distance_mangroves), y=mulloidichthys_flavolineatus)) + xlab('Distance to mangroves (m)') + ylab('Abundance Mulloidichthys flavolineatus')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$mulloidichthys_flavolineatus, by=list(distance_mangroves=df.sample_data$distance_mangroves), FUN=mean)
agg$mulloidichthys_flavolineatus <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r m_par_bar}

plt <- ggplot(df.sample_data, aes(x=log(distance_mangroves), y=parupeneus_barberinoides)) + xlab('Distance to mangroves (m)') + ylab('Abundance Parupeneus barberinoides')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$parupeneus_barberinoides, by=list(distance_mangroves=df.sample_data$distance_mangroves), FUN=mean)
agg$parupeneus_barberinoides <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```

```{r m_par_bar2}

plt <- ggplot(df.sample_data, aes(x=log(distance_mangroves), y=parupeneus_barberinus)) + xlab('Distance to mangroves (m)') + ylab('Abundance Parupeneus barberinus')

plt <- plt + geom_point()

agg <- aggregate(df.sample_data$parupeneus_barberinus, by=list(distance_mangroves=df.sample_data$distance_mangroves), FUN=mean)
agg$parupeneus_barberinus <- agg$x 

plt <- plt + geom_line(data=agg)
plt 
```
