---
title: "GLM on abundance_pres"
author: 'Dirkje Verhoeven, Dolf Andringa, Annelies Andringa: Marine Conservation Philippines'
date: "02 June 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
load('data.RDa') #load the data
library('vegan')
library('ggplot2')
library('PMCMR')
library('formula.tools')
nursery_species <- subset(df.species_all, df.species_all$nursery) 
```

## Calculate some info per sample

```{r calculation}
#calculate the Shannon-Wiener diversity (with diversity function from vegan package) for all species
df.sample_data$diversity <- apply(df.sample_data[df.species_all$colname], MARGIN=1, diversity)
#calculate the Shannon-Wiener diversity (with diversity function from vegan package) for nursery species
df.sample_data$nursery_diversity <- apply(df.sample_data[nursery_species$colname], MARGIN=1, diversity)

#calculate number of species for all species by summing the presence/absence columns for those species
df.sample_data$num_species <- apply(df.sample_data[c(df.species_all$colname_pres)],MARGIN=1,sum)
#calculate number of species for nursery species by summing the presence/absence columns for those species
df.sample_data$num_nursery_species <- apply(df.sample_data[c(nursery_species$colname_pres)],MARGIN=1,sum)

#calculate number of fish
df.sample_data$num_fish <- apply(df.sample_data[c(df.species_all$colname)],MARGIN=1,sum)
#calculate number of nursery fish
df.sample_data$num_nursery_fish <- apply(df.sample_data[c(nursery_species$colname)],MARGIN=1,sum)

df.sample_data <- merge(x=df.sample_data, y=df.sites, by.x="location", by.y="name", all.x=TRUE)
```

## Nursery species

```{r subset_nursery_species}
nursery_columns <- c(c("location","depth","transect","date","nursery_diversity","num_nursery_species","num_nursery_fish"),nursery_species$colname, nursery_species$colname_pres) #columns for nursery species analysis
df.nursery_sample_data <- df.sample_data[nursery_columns] # subset of the data with only the nursery species
```

##GLM family=Poisson on abundance_pres

Independent variables: size_seagrass, distance_seagrass, mpa, depth, north

```{r glm_Pois_nur_loop} 
glm_tab <- data.frame(species=c(), coefficient=c(), pvalue=c())

speciesrows <- c(1:3,25:28,36,39,40,42,47,52:54,58,66,84:86,88,91:100,102:104)
for (spnum in speciesrows){
  sp <- df.species_all[spnum,]
  print(sp$colname)
  n <- subset(df.sample_data, df.sample_data[c(sp$colname_pres)] > 0)
  if(nrow(n)<5){
    print("Less than 5 rows remaining in subset")
    next
  }
  if(length(unique(n$depth))==1 & length(unique(n$mpa))>1){
    formula <- n[,c(sp$colname)] ~ n$distance_seagrass * n$size_seagrass * n$mpa * n$north
  }
  else if (length(unique(n$depth))>1 & length(unique(n$mpa))==1){
    formula <- n[,c(sp$colname)] ~ n$distance_seagrass * n$size_seagrass * n$depth * n$north  
  }
  else if (length(unique(n$depth))==1 & length(unique(n$mpa))==1){
    formula <- n[,c(sp$colname)] ~ n$distance_seagrass * n$size_seagrass * n$north  
  }
  else{
    formula <- n[,c(sp$colname)] ~ n$distance_seagrass * n$size_seagrass * n$mpa * n$depth * n$north  
  }
  print(paste("Formula",sp$colname,":",as.character(formula)))
  res <- NULL
  tryCatch(
  res <- glm(formula, family="poisson"),
    error=function(e){ print("GLM kon niet uitgevoerd worden.");print(geterrmessage())}
  )
  if(is.null(res)){
    next
  }
  
  coefs <- as.data.frame(coef(summary(res)))
  coefs <- subset(coefs,coefs$`Pr(>|z|)`<=0.05)
  coefs <- data.frame(species=rep(sp$colname,nrow(coefs)),coefficient=rownames(coefs),pvalue=coefs$`Pr(>|z|)`)
  coefs <- subset(coefs, coefs$coefficient != '(Intercept)')
  
  if(nrow(coefs)==0){
    next
  }
  glm_tab <- rbind(glm_tab, coefs)
  print(paste("AIC",sp$colname,": ",summary(res)$aic))
  par(mfrow=c(1,2)) 
  plot(fitted(res),residuals(res),xlab="Fitted values", ylab="Residuals", abline(h=0, lty=2))
  title(sp$colname)
  tryCatch( 
    lines(smooth.spline(fitted(res), residuals(res))), 
    error=function(e){}  )
  qqnorm(res$residuals)
  qqline(res$residuals) 
}
```

```{r glm_Pois_nur_table}
knitr::kable(glm_tab, escape=TRUE)
```  

log(size)

```{r glm_nur_Lsize_loop} 
glm_tab <- data.frame(species=c(), coefficient=c(), pvalue=c())

speciesrows <- c(1:3,25:28,36,39,40,42,47,52:54,58,66,84:86,88,91:100,102:104)
for (spnum in speciesrows){
  sp <- df.species_all[spnum,]
  print(sp$colname)
  n <- subset(df.sample_data, df.sample_data[c(sp$colname_pres)] > 0)
  if(nrow(n)<5){
    print("Less than 5 rows remaining in subset")
    next
  }
  if(length(unique(n$depth))==1 & length(unique(n$mpa))>1){
    formula <- n[,c(sp$colname)] ~ n$distance_seagrass * log(n$size_seagrass) * n$mpa * n$north
  }
  else if (length(unique(n$depth))>1 & length(unique(n$mpa))==1){
    formula <- n[,c(sp$colname)] ~ n$distance_seagrass * log(n$size_seagrass) * n$depth * n$north  
  }
  else if (length(unique(n$depth))==1 & length(unique(n$mpa))==1){
    formula <- n[,c(sp$colname)] ~ n$distance_seagrass * log(n$size_seagrass) * n$north  
  }
  else{
    formula <- n[,c(sp$colname)] ~ n$distance_seagrass * log(n$size_seagrass) * n$mpa * n$depth * n$north  
  }
  print(paste("Formula",sp$colname,":",as.character(formula)))
  res <- NULL
  tryCatch(
  res <- glm(formula, family="poisson"),
    error=function(e){ print("GLM kon niet uitgevoerd worden.");print(geterrmessage())}
  )
  if(is.null(res)){
    next
  }
  
  coefs <- as.data.frame(coef(summary(res)))
  coefs <- subset(coefs,coefs$`Pr(>|z|)`<=0.05)
  coefs <- data.frame(species=rep(sp$colname,nrow(coefs)),coefficient=rownames(coefs),pvalue=coefs$`Pr(>|z|)`)
  coefs <- subset(coefs, coefs$coefficient != '(Intercept)')
  
  if(nrow(coefs)==0){
    next
  }
  glm_tab <- rbind(glm_tab, coefs)
  print(paste("AIC",sp$colname,": ",summary(res)$aic))
  par(mfrow=c(1,2)) 
  plot(fitted(res),residuals(res),xlab="Fitted values", ylab="Residuals", abline(h=0, lty=2))
  title(sp$colname)
  tryCatch( 
    lines(smooth.spline(fitted(res), residuals(res))), 
    error=function(e){}  )
  qqnorm(res$residuals)
  qqline(res$residuals) 
}
```

```{r glm_nur_Lsize_table}
knitr::kable(glm_tab, escape=TRUE)
```  

log(distance)

```{r glm_nur_Ldist_loop} 
glm_tab <- data.frame(species=c(), coefficient=c(), pvalue=c())

speciesrows <- c(1:3,25:28,36,39,40,42,47,52:54,58,66,84:86,88,91:100,102:104)
for (spnum in speciesrows){
  sp <- df.species_all[spnum,]
  print(sp$colname)
  n <- subset(df.sample_data, df.sample_data[c(sp$colname_pres)] > 0)
  if(nrow(n)<5){
    print("Less than 5 rows remaining in subset")
    next
  }
  if(length(unique(n$depth))==1 & length(unique(n$mpa))>1){
    formula <- n[,c(sp$colname)] ~ log(n$distance_seagrass) * n$size_seagrass * n$mpa * n$north
  }
  else if (length(unique(n$depth))>1 & length(unique(n$mpa))==1){
    formula <- n[,c(sp$colname)] ~ log(n$distance_seagrass) * n$size_seagrass * n$depth * n$north  
  }
  else if (length(unique(n$depth))==1 & length(unique(n$mpa))==1){
    formula <- n[,c(sp$colname)] ~ log(n$distance_seagrass) * n$size_seagrass * n$north  
  }
  else{
    formula <- n[,c(sp$colname)] ~ log(n$distance_seagrass) * n$size_seagrass * n$mpa * n$depth * n$north  
  }
  print(paste("Formula",sp$colname,":",as.character(formula)))
  res <- NULL
  tryCatch(
  res <- glm(formula, family="poisson"),
    error=function(e){ print("GLM kon niet uitgevoerd worden.");print(geterrmessage())}
  )
  if(is.null(res)){
    next
  }
  
  coefs <- as.data.frame(coef(summary(res)))
  coefs <- subset(coefs,coefs$`Pr(>|z|)`<=0.05)
  coefs <- data.frame(species=rep(sp$colname,nrow(coefs)),coefficient=rownames(coefs),pvalue=coefs$`Pr(>|z|)`)
  coefs <- subset(coefs, coefs$coefficient != '(Intercept)')
  
  if(nrow(coefs)==0){
    next
  }
  glm_tab <- rbind(glm_tab, coefs)
  print(paste("AIC",sp$colname,": ",summary(res)$aic))
  par(mfrow=c(1,2)) 
  plot(fitted(res),residuals(res),xlab="Fitted values", ylab="Residuals", abline(h=0, lty=2))
  title(sp$colname)
  tryCatch( 
    lines(smooth.spline(fitted(res), residuals(res))), 
    error=function(e){}  )
  qqnorm(res$residuals)
  qqline(res$residuals) 
}
```

```{r glm_nur_Ldist_table}
knitr::kable(glm_tab, escape=TRUE)
```  

log(size) & log (distance)

```{r glm_nur_Lsize-dist_loop} 
glm_tab <- data.frame(species=c(), coefficient=c(), pvalue=c())

speciesrows <- c(1:3,25:28,36,39,40,42,47,52:54,58,66,84:86,88,91:100,102:104)
for (spnum in speciesrows){
  sp <- df.species_all[spnum,]
  print(sp$colname)
  n <- subset(df.sample_data, df.sample_data[c(sp$colname_pres)] > 0)
  if(nrow(n)<5){
    print("Less than 5 rows remaining in subset")
    next
  }
  if(length(unique(n$depth))==1 & length(unique(n$mpa))>1){
    formula <- n[,c(sp$colname)] ~ log(n$distance_seagrass) * log(n$size_seagrass) * n$mpa * n$north
  }
  else if (length(unique(n$depth))>1 & length(unique(n$mpa))==1){
    formula <- n[,c(sp$colname)] ~ log(n$distance_seagrass) * log(n$size_seagrass) * n$depth * n$north  
  }
  else if (length(unique(n$depth))==1 & length(unique(n$mpa))==1){
    formula <- n[,c(sp$colname)] ~ log(n$distance_seagrass) * log(n$size_seagrass) * n$north  
  }
  else{
    formula <- n[,c(sp$colname)] ~ log(n$distance_seagrass) * log(n$size_seagrass) * n$mpa * n$depth * n$north  
  }
  print(paste("Formula",sp$colname,":",as.character(formula)))
  res <- NULL
  tryCatch(
  res <- glm(formula, family="poisson"),
    error=function(e){ print("GLM kon niet uitgevoerd worden.");print(geterrmessage())}
  )
  if(is.null(res)){
    next
  }
  
  coefs <- as.data.frame(coef(summary(res)))
  coefs <- subset(coefs,coefs$`Pr(>|z|)`<=0.05)
  coefs <- data.frame(species=rep(sp$colname,nrow(coefs)),coefficient=rownames(coefs),pvalue=coefs$`Pr(>|z|)`)
  coefs <- subset(coefs, coefs$coefficient != '(Intercept)')
  
  if(nrow(coefs)==0){
    next
  }
  glm_tab <- rbind(glm_tab, coefs)
  print(paste("AIC",sp$colname,": ",summary(res)$aic))
  par(mfrow=c(1,2)) 
  plot(fitted(res),residuals(res),xlab="Fitted values", ylab="Residuals", abline(h=0, lty=2))
  title(sp$colname)
  tryCatch( 
    lines(smooth.spline(fitted(res), residuals(res))), 
    error=function(e){}  )
  qqnorm(res$residuals)
  qqline(res$residuals) 
}
```

```{r glm_nur_Lsize-dist_table}
knitr::kable(glm_tab, escape=TRUE)
```  

##GLM family=Gaussian on abundance_pres

log(abundance)

```{r glmnur_Labun_loop} 
glm_tab <- data.frame(species=c(), coefficient=c(), pvalue=c())

speciesrows <- c(1:3,25:28,36,39,40,42,47,52:54,58,66,84:86,88,91:100,102:104)
for (spnum in speciesrows){
  sp <- df.species_all[spnum,]
  print(sp$colname)
  n <- subset(df.sample_data, df.sample_data[c(sp$colname_pres)] > 0)
  if(nrow(n)<5){
    print("Less than 5 rows remaining in subset")
    next
  }
  if(length(unique(n$depth))==1 & length(unique(n$mpa))>1){
    formula <- log(n[,c(sp$colname)]) ~ n$distance_seagrass * n$size_seagrass * n$mpa * n$north
  }
  else if (length(unique(n$depth))>1 & length(unique(n$mpa))==1){
    formula <- log(n[,c(sp$colname)]) ~ n$distance_seagrass * n$size_seagrass * n$depth * n$north  
  }
  else if (length(unique(n$depth))==1 & length(unique(n$mpa))==1){
    formula <- log(n[,c(sp$colname)]) ~ n$distance_seagrass * n$size_seagrass * n$north  
  }
  else{
    formula <- log(n[,c(sp$colname)]) ~ n$distance_seagrass * n$size_seagrass * n$mpa * n$depth * n$north  
  }
  print(paste("Formula",sp$colname,":",as.character(formula)))
  res <- NULL
  tryCatch(
  res <- glm(formula, family="gaussian"),
    error=function(e){ print("GLM kon niet uitgevoerd worden.");print(geterrmessage())}
  )
  if(is.null(res)){
    next
  }
  
  coefs <- as.data.frame(coef(summary(res)))
  coefs <- subset(coefs,coefs$`Pr(>|z|)`<=0.05)
  coefs <- data.frame(species=rep(sp$colname,nrow(coefs)),coefficient=rownames(coefs),pvalue=coefs$`Pr(>|z|)`)
  coefs <- subset(coefs, coefs$coefficient != '(Intercept)')
  
  if(nrow(coefs)==0){
    next
  }
  glm_tab <- rbind(glm_tab, coefs)
  print(paste("AIC",sp$colname,": ",summary(res)$aic))
  par(mfrow=c(1,2)) 
  plot(fitted(res),residuals(res),xlab="Fitted values", ylab="Residuals", abline(h=0, lty=2))
  title(sp$colname)
  tryCatch( 
    lines(smooth.spline(fitted(res), residuals(res))), 
    error=function(e){}  )
  qqnorm(res$residuals)
  qqline(res$residuals) 
}
```

```{r glm_nur_Labun_table}
knitr::kable(glm_tab, escape=TRUE)
```  

log(abundance) & log(size)

```{r glm_nur_Labun-size_loop} 
glm_tab <- data.frame(species=c(), coefficient=c(), pvalue=c())

speciesrows <- c(1:3,25:28,36,39,40,42,47,52:54,58,66,84:86,88,91:100,102:104)
for (spnum in speciesrows){
  sp <- df.species_all[spnum,]
  print(sp$colname)
  n <- subset(df.sample_data, df.sample_data[c(sp$colname_pres)] > 0)
  if(nrow(n)<5){
    print("Less than 5 rows remaining in subset")
    next
  }
  if(length(unique(n$depth))==1 & length(unique(n$mpa))>1){
    formula <- log(n[,c(sp$colname)]) ~ n$distance_seagrass * log(n$size_seagrass) * n$mpa * n$north
  }
  else if (length(unique(n$depth))>1 & length(unique(n$mpa))==1){
    formula <- log(n[,c(sp$colname)]) ~ n$distance_seagrass * log(n$size_seagrass) * n$depth * n$north  
  }
  else if (length(unique(n$depth))==1 & length(unique(n$mpa))==1){
    formula <- log(n[,c(sp$colname)]) ~ n$distance_seagrass * log(n$size_seagrass) * n$north  
  }
  else{
    formula <- log(n[,c(sp$colname)]) ~ n$distance_seagrass * log(n$size_seagrass) * n$mpa * n$depth * n$north  
  }
  print(paste("Formula",sp$colname,":",as.character(formula)))
  res <- NULL
  tryCatch(
  res <- glm(formula, family="gaussian"),
    error=function(e){ print("GLM kon niet uitgevoerd worden.");print(geterrmessage())}
  )
  if(is.null(res)){
    next
  }
  
  coefs <- as.data.frame(coef(summary(res)))
  coefs <- subset(coefs,coefs$`Pr(>|z|)`<=0.05)
  coefs <- data.frame(species=rep(sp$colname,nrow(coefs)),coefficient=rownames(coefs),pvalue=coefs$`Pr(>|z|)`)
  coefs <- subset(coefs, coefs$coefficient != '(Intercept)')
  
  if(nrow(coefs)==0){
    next
  }
  glm_tab <- rbind(glm_tab, coefs)
  print(paste("AIC",sp$colname,": ",summary(res)$aic))
  par(mfrow=c(1,2)) 
  plot(fitted(res),residuals(res),xlab="Fitted values", ylab="Residuals", abline(h=0, lty=2))
  title(sp$colname)
  tryCatch( 
    lines(smooth.spline(fitted(res), residuals(res))), 
    error=function(e){}  )
  qqnorm(res$residuals)
  qqline(res$residuals) 
}
```

```{r glm_nur_Labun-size_table}
knitr::kable(glm_tab, escape=TRUE)
```  

log(abundance) & log(distance)

```{r glm_nur_Labun-dist_loop} 
glm_tab <- data.frame(species=c(), coefficient=c(), pvalue=c())

speciesrows <- c(1:3,25:28,36,39,40,42,47,52:54,58,66,84:86,88,91:100,102:104)
for (spnum in speciesrows){
  sp <- df.species_all[spnum,]
  print(sp$colname)
  n <- subset(df.sample_data, df.sample_data[c(sp$colname_pres)] > 0)
  if(nrow(n)<5){
    print("Less than 5 rows remaining in subset")
    next
  }
  if(length(unique(n$depth))==1 & length(unique(n$mpa))>1){
    formula <- log(n[,c(sp$colname)]) ~ log(n$distance_seagrass) * n$size_seagrass * n$mpa * n$north
  }
  else if (length(unique(n$depth))>1 & length(unique(n$mpa))==1){
    formula <- log(n[,c(sp$colname)]) ~ log(n$distance_seagrass) * n$size_seagrass * n$depth * n$north  
  }
  else if (length(unique(n$depth))==1 & length(unique(n$mpa))==1){
    formula <- log(n[,c(sp$colname)]) ~ log(n$distance_seagrass) * n$size_seagrass * n$north  
  }
  else{
    formula <- log(n[,c(sp$colname)]) ~ log(n$distance_seagrass) * n$size_seagrass * n$mpa * n$depth * n$north  
  }
  print(paste("Formula",sp$colname,":",as.character(formula)))
  res <- NULL
  tryCatch(
  res <- glm(formula, family="gaussian"),
    error=function(e){ print("GLM kon niet uitgevoerd worden.");print(geterrmessage())}
  )
  if(is.null(res)){
    next
  }
  
  coefs <- as.data.frame(coef(summary(res)))
  coefs <- subset(coefs,coefs$`Pr(>|z|)`<=0.05)
  coefs <- data.frame(species=rep(sp$colname,nrow(coefs)),coefficient=rownames(coefs),pvalue=coefs$`Pr(>|z|)`)
  coefs <- subset(coefs, coefs$coefficient != '(Intercept)')
  
  if(nrow(coefs)==0){
    next
  }
  glm_tab <- rbind(glm_tab, coefs)
  print(paste("AIC",sp$colname,": ",summary(res)$aic))
  par(mfrow=c(1,2)) 
  plot(fitted(res),residuals(res),xlab="Fitted values", ylab="Residuals", abline(h=0, lty=2))
  title(sp$colname)
  tryCatch( 
    lines(smooth.spline(fitted(res), residuals(res))), 
    error=function(e){}  )
  qqnorm(res$residuals)
  qqline(res$residuals) 
}
```

```{r glm_nur_Lbun-dist_table}
knitr::kable(glm_tab, escape=TRUE)
```  

log(abundance), log(size) & log (distance)

```{r glm_nur_Labun-size-dist_loop} 
glm_tab <- data.frame(species=c(), coefficient=c(), pvalue=c())

speciesrows <- c(1:3,25:28,36,39,40,42,47,52:54,58,66,84:86,88,91:100,102:104)
for (spnum in speciesrows){
  sp <- df.species_all[spnum,]
  print(sp$colname)
  n <- subset(df.sample_data, df.sample_data[c(sp$colname_pres)] > 0)
  if(nrow(n)<5){
    print("Less than 5 rows remaining in subset")
    next
  }
  if(length(unique(n$depth))==1 & length(unique(n$mpa))>1){
    formula <- log(n[,c(sp$colname)]) ~ log(n$distance_seagrass) * log(n$size_seagrass) * n$mpa * n$north
  }
  else if (length(unique(n$depth))>1 & length(unique(n$mpa))==1){
    formula <- log(n[,c(sp$colname)]) ~ log(n$distance_seagrass) * log(n$size_seagrass) * n$depth * n$north  
  }
  else if (length(unique(n$depth))==1 & length(unique(n$mpa))==1){
    formula <- log(n[,c(sp$colname)]) ~ log(n$distance_seagrass) * log(n$size_seagrass) * n$north  
  }
  else{
    formula <- log(n[,c(sp$colname)]) ~ log(n$distance_seagrass) * log(n$size_seagrass) * n$mpa * n$depth * n$north  
  }
  print(paste("Formula",sp$colname,":",as.character(formula)))
  res <- NULL
  tryCatch(
  res <- glm(formula, family="gaussian"),
    error=function(e){ print("GLM kon niet uitgevoerd worden.");print(geterrmessage())}
  )
  if(is.null(res)){
    next
  }
  
  coefs <- as.data.frame(coef(summary(res)))
  coefs <- subset(coefs,coefs$`Pr(>|z|)`<=0.05)
  coefs <- data.frame(species=rep(sp$colname,nrow(coefs)),coefficient=rownames(coefs),pvalue=coefs$`Pr(>|z|)`)
  coefs <- subset(coefs, coefs$coefficient != '(Intercept)')
  
  if(nrow(coefs)==0){
    next
  }
  glm_tab <- rbind(glm_tab, coefs)
  print(paste("AIC",sp$colname,": ",summary(res)$aic))
  par(mfrow=c(1,2)) 
  plot(fitted(res),residuals(res),xlab="Fitted values", ylab="Residuals", abline(h=0, lty=2))
  title(sp$colname)
  tryCatch( 
    lines(smooth.spline(fitted(res), residuals(res))), 
    error=function(e){}  )
  qqnorm(res$residuals)
  qqline(res$residuals) 
}
```

```{r glm_nur_Labun-size-dist_table}
knitr::kable(glm_tab, escape=TRUE)
```  
